all:
  children:
    windows:
      hosts:
        192.168.20.103:


      vars:
        ansible_connection: ssh

        ansible_shell_type: powershell

        ansible_user: Admin
        ansible_password: "Admin"